# Generated by Django 4.2.4 on 2023-10-27 07:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradoresEliminados',
            fields=[
                ('ID_usuario', models.IntegerField(db_column='ID_usuario', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('mail', models.CharField(db_column='mail', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
                ('fecha_eliminado', models.DateField(db_column='fecha_eliminado')),
            ],
            options={
                'db_table': 'administradores_eliminados',
            },
        ),
        migrations.CreateModel(
            name='CajerosEliminados',
            fields=[
                ('ID_usuario', models.IntegerField(db_column='ID_usuario', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('mail', models.CharField(db_column='mail', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
                ('fecha_eliminado', models.DateField(db_column='fecha_eliminado')),
            ],
            options={
                'db_table': 'cajeros_eliminados',
            },
        ),
        migrations.CreateModel(
            name='CitasEliminados',
            fields=[
                ('ID_cita', models.IntegerField(db_column='ID_cita', primary_key=True, serialize=False, unique=True)),
                ('ID_paciente', models.IntegerField(db_column='ID_paciente')),
                ('nombre_paciente', models.CharField(db_column='nombre_paciente', max_length=45)),
                ('apellido_paciente', models.CharField(db_column='apellido_paciente', max_length=45)),
                ('ID_doctor', models.IntegerField(db_column='ID_doctor')),
                ('nombre_doctor', models.CharField(db_column='nombre_doctor', max_length=45)),
                ('apellido_doctor', models.CharField(db_column='apellido_doctor', max_length=45)),
                ('tipo', models.CharField(db_column='tipo', max_length=45)),
                ('fecha_eliminado', models.DateField(db_column='fecha_eliminado')),
                ('fecha', models.DateField(db_column='fecha', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'citas_eliminados',
            },
        ),
        migrations.CreateModel(
            name='DoctoresEliminados',
            fields=[
                ('ID_usuario', models.IntegerField(db_column='ID_usuario', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('mail', models.CharField(db_column='mail', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
                ('especialidad', models.CharField(db_column='especialidad', max_length=45)),
                ('fecha_eliminado', models.DateField(db_column='fecha_eliminado')),
            ],
            options={
                'db_table': 'doctores_eliminados',
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('ID_especialidad', models.AutoField(db_column='ID_especialidad', primary_key=True, serialize=False)),
                ('especialidad', models.CharField(db_column='especialidad', max_length=45)),
            ],
            options={
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='EspecialidadesEliminados',
            fields=[
                ('ID_especialidad', models.IntegerField(db_column='ID_especialidad', primary_key=True, serialize=False, unique=True)),
                ('especialidad', models.CharField(db_column='especialidad', max_length=45)),
                ('fecha_eliminado', models.DateField(db_column='fecha_eliminado')),
            ],
            options={
                'db_table': 'especialidades_eliminados',
            },
        ),
        migrations.CreateModel(
            name='PacientesEliminados',
            fields=[
                ('ID_usuario', models.IntegerField(db_column='ID_usuario', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('mail', models.CharField(db_column='mail', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
                ('situacion', models.CharField(db_column='situacion', max_length=200)),
                ('observaciones', models.CharField(db_column='observaciones', max_length=200)),
                ('fecha_modificacion', models.DateField(db_column='fecha_modificacion')),
                ('fecha_eliminado', models.DateField(db_column='fecha_eliminado')),
            ],
            options={
                'db_table': 'pacientes_eliminados',
            },
        ),
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('ID_tipo', models.AutoField(db_column='ID_tipo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=45)),
            ],
            options={
                'db_table': 'tipos_cita',
            },
        ),
        migrations.CreateModel(
            name='TipoCitaEliminados',
            fields=[
                ('ID_tipo', models.IntegerField(db_column='ID_tipo', primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(db_column='tipo', max_length=45)),
                ('fecha_eliminado', models.DateField(db_column='fecha_eliminado')),
            ],
            options={
                'db_table': 'tipos_citas_eliminados',
            },
        ),
        migrations.CreateModel(
            name='TurnosEliminados',
            fields=[
                ('ID_turno', models.IntegerField(db_column='ID_turno', primary_key=True, serialize=False, unique=True)),
                ('ID_usuario', models.IntegerField(db_column='ID_usuario')),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('tipo', models.CharField(db_column='tipo', max_length=45)),
                ('especialidad', models.CharField(db_column='especialidad', max_length=45)),
                ('estado', models.CharField(db_column='estado', max_length=45)),
                ('fecha_reserva', models.DateField(db_column='fecha_reserva')),
                ('fecha_turnos', models.DateField(db_column='fecha_turnos')),
                ('fecha_eliminado', models.DateField(db_column='fecha_eliminado')),
            ],
            options={
                'db_table': 'turnos_eliminados',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_usuario', models.IntegerField(db_column='ID_usuario', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('mail', models.CharField(db_column='mail', max_length=45, unique=True)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
                ('password', models.CharField(db_column='password', max_length=45)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsuariosEliminados',
            fields=[
                ('ID_usuario', models.IntegerField(db_column='ID_usuario', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('mail', models.CharField(db_column='mail', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
                ('password', models.CharField(db_column='pass', max_length=45)),
                ('fecha_eliminado', models.DateField()),
            ],
            options={
                'db_table': 'usuarios_eliminados',
            },
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id_administrador', models.OneToOneField(db_column='ID_administrador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equinacea_web.usuarios')),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Cajeros',
            fields=[
                ('ID_cajero', models.OneToOneField(db_column='ID_cajero', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equinacea_web.usuarios')),
            ],
            options={
                'db_table': 'cajeros',
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('ID_paciente', models.OneToOneField(db_column='ID_paciente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equinacea_web.usuarios')),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('paciente', models.OneToOneField(db_column='paciente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equinacea_web.pacientes')),
                ('situacion', models.CharField(db_column='situacion', default=' ', max_length=200)),
                ('observaciones', models.CharField(db_column='observaciones', default=' ', max_length=200)),
                ('fecha_modificacion', models.DateField(db_column='fecha_modificacion', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('ID_turno', models.AutoField(db_column='ID_turno', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='estado', max_length=45)),
                ('fecha_reserva', models.DateField(db_column='fecha_reserva')),
                ('fecha_turnos', models.DateField(db_column='fecha_turnos')),
                ('especialidad', models.ForeignKey(db_column='especialidad', on_delete=django.db.models.deletion.CASCADE, to='equinacea_web.especialidades')),
                ('tipo', models.ForeignKey(db_column='tipo', on_delete=django.db.models.deletion.CASCADE, to='equinacea_web.tipocita')),
                ('paciente', models.ForeignKey(db_column='paciente', on_delete=django.db.models.deletion.CASCADE, to='equinacea_web.pacientes')),
            ],
            options={
                'db_table': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('ID_doctor', models.OneToOneField(db_column='ID_doctor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equinacea_web.usuarios')),
                ('disponibilidad', models.BooleanField(db_column='disponibilidad', default=True)),
                ('especialidad', models.ForeignKey(db_column='especialidad', on_delete=django.db.models.deletion.CASCADE, to='equinacea_web.especialidades')),
            ],
            options={
                'db_table': 'doctores',
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('ID_cita', models.AutoField(db_column='ID_cita', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha', default=django.utils.timezone.now)),
                ('tipo', models.ForeignKey(db_column='tipo', on_delete=django.db.models.deletion.CASCADE, to='equinacea_web.tipocita')),
                ('doctor', models.ForeignKey(db_column='doctor', on_delete=django.db.models.deletion.CASCADE, to='equinacea_web.doctores')),
                ('paciente', models.ForeignKey(db_column='paciente', on_delete=django.db.models.deletion.CASCADE, to='equinacea_web.pacientes')),
            ],
            options={
                'db_table': 'citas',
            },
        ),
    ]
